import os
from building import *

cwd = GetCurrentDir()
src	= Glob('*.c')
src += Glob(os.path.join("portable", "rt-thread", "*.c"))
src += Glob(os.path.join("portable", "MemMang", "heap_3.c"))

CPPPATH = [os.path.join(cwd, "include"), os.path.join(cwd, "portable", "rt-thread")]

group = DefineGroup('FreeRTOS', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
