import os
from building import *

cwd = GetCurrentDir()
src	= Glob('*.c')
CPPPATH = [os.path.join(cwd, "include", "freertos"), os.path.join(cwd, "include")]

if (GetDepend(['PKG_USING_ESP_IDF']):
  src += Split("""
    portable/esp-idf/port_rt.c
    portable/esp-idf/riscv/port.c
    portable/esp-idf/port_common.c
  """)
  CPPPATH += Split("""
    portable/esp-idf/riscv/include
    portable/esp-idf/riscv/include/freertos
  """)

if GetDepend('PKG_FREERTOS_WRAPPER_USING_RTTHREAD') :
  src += Glob(os.path.join("portable", "rt-thread", "*.c"))
  CPPPATH += [ os.path.join(cwd, "portable", "rt-thread")]

if GetDepend('PKG_FREERTOS_WRAPPER_USING_MEMANG') :
  src += Glob(os.path.join("portable", "MemMang", "heap_3.c"))

group = DefineGroup('FreeRTOS', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
